remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [techneo's blog]
description: [Musings on ideas, projects, technology, and everything in between]
